### PR TITLE
Set up initial seed for `longitudinal` app for reproducibility

### LINKED ISSUE #44: [Bug]: `longitudinal` Reproducible code fails/warnings
### What happened?

* ADLB pipeline uses random sampling without a common seed, so the reproducible code fails

image

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by averissimo**
Fixes #44 

It also replaces `filter` parameter  with `datanames`

### CODE REVIEW

File: longitudinal/app.R [hunk 1]
```diff
@@ -154,6 +154,9 @@ var_labels(ADSL) <- c(adsl_labels)
 # other values can be adjusted for as well of course but this is study specific pre-processing that needs to be done
 
 # adjust select based on your study specifics
+
+set.seed(1, kind = "Mersenne-Twister") # Reproducible code due to `sample` calls
```
Comment (gogonzo) [inline longitudinal/app.R:158]: Why this? Is there any randomness?

Comment (vedhav) [reply longitudinal/app.R:158]: Yeah, we take `sample()` in two places within the `ADLB_SUBSET <- ADLB`.
And, I confirm that this fix works.

Comment (gogonzo) [reply longitudinal/app.R:158]: good catch 👍

**Review by gogonzo — APPROVED** [review]
