### PR TITLE
Make JoinKeys related changes due to refactor

### LINKED ISSUE #95: Fix the `python` app after the connector is created for it.
Right now the python app is broken because the data is specified using the `teal.data::python_dataset_connector()` which returns a `TealDatasetConnector` object which no longer works with the new `join_keys`.

### PR DESCRIPTION
**Pull request by gogonzo**
Open over https://github.com/insightsengineering/teal.gallery/pull/75 to implement improved JoinKeys API

Also closes #95 

Fixed apps:

- [x] basic-teal
- [x] exploratory
- [x] safety
- [x] efficacy
- [x] patient-profile
- [x] early-dev
- [x] longitudinal
- [x] RNA-seq
- [x] python

Full installation 
```r
staged.dependencies::dependency_table(
  project = "insightsengineering/teal.data@https://github.com",
  project_type = "repo@host",
  ref = "591-migrate-to-teal_data@78_simplify_joinkeys@main",
  verbose = 1
) |> staged.dependencies::install_deps(install_direction = "all")

```

### CODE REVIEW

File: efficacy/app.R [hunk 1]
```diff
@@ -1,62 +1,73 @@
...
+    )
+  teal.data::col_labels(ADQS) <- adqs_labels
+})
+
+# set datanames
+datanames <- c("ADSL", "ADTTE", "ADRS", "ADQS")
+datanames(data) <- datanames
+
+# set join_keys
+data@join_keys <- cdisc_join_keys(!!!datanames)
```
Comment (m7pr) [inline efficacy/app.R:62]:
```suggestion
join_keys(data) <- cdisc_join_keys(!!!datanames)
```

File: exploratory/app.R [hunk 2]
```diff
@@ -1,62 +1,61 @@
...
+    )
+})
+
+datanames <- c("ADSL", "ADRS", "ADLB", "ADLBPCA")
+datanames(data) <- datanames
+
+join_keys <- cdisc_join_keys(!!!datanames)
+join_keys["ADLBPCA"] <- c("USUBJID", "STUDYID", "PARAMCD", "AVISIT")
+join_keys["ADLBPCA", "ADSL"] <- c("USUBJID", "STUDYID")
+data@join_keys <- join_keys
```
Comment (m7pr) [inline exploratory/app.R:52]:
```suggestion
join_keys(data) <- join_keys
```

File: safety/app.R [hunk 3]
```diff
@@ -8,134 +6,148 @@ library(teal.modules.clinical)
...
-      TMPFL_REL = "Related AE",
-      TMPFL_GR5 = "Grade 5 AE",
-      TMP_SMQ01 = aesi_label(dat$SMQ01NAM, dat$SMQ01SC),
-      TMP_SMQ02 = aesi_label(dat$SMQ02NAM, dat$SMQ02SC),
-      TMP_CQ01 = aesi_label(dat$CQ01NAM)
-    )
-}
+datanames <- c("ADSL", "ADAE", "ADAETTE", "ADEX", "ADLB", "ADEG", "ADVS", "ADCM")
+datanames(data) <- datanames
+data@join_keys <- cdisc_join_keys(!!!datanames)
```
Comment (m7pr) [inline safety/app.R:127]:
```suggestion
join_keys(data) <- cdisc_join_keys(!!!datanames)
```

**Comment by vedhav** [comment]
Have switched the target to `dev` because for now, we can only have successful deployments with multiple branches. Soon, we plan to see if there is something better we can do about this.

**Comment by vedhav** [comment]
After the `teal_data_module` is created in the [teal PR #957](https://github.com/insightsengineering/teal/pull/957) and the new `python_dataset_connector` is created the python app will be fixed.

File: early-dev/app.R [hunk 4]
```diff
@@ -1,141 +1,178 @@
...
+datanames(data) <- datanames
+
+# set join keys
+join_keys(data) <- cdisc_join_keys(!!!datanames) # get default keys by name
+join_keys(data)["ADTR"] <- c("STUDYID", "USUBJID", "PARAMCD", "AVISIT")
+join_keys(data)["ADTRWF"] <- c("STUDYID", "USUBJID", "PARAMCD", "AVISIT")
+join_keys(data)["ADRSSWIM"] <- c("STUDYID", "USUBJID", "PARAMCD", "AVISIT")
+join_keys(data)["ADTR", "ADSL"] <- c("STUDYID", "USUBJID")
+join_keys(data)["ADTRWF", "ADSL"] <- c("STUDYID", "USUBJID")
+join_keys(data)["ADRSSWIM", "ADSL"] <- c("STUDYID", "USUBJID")
```
Comment (kartikeyakirar) [inline early-dev/app.R:154]:
```suggestion
join_keys(data) <- default_cdisc_join_keys[datanames] # get default keys by name
join_keys(data)["ADTR"] <- c("STUDYID", "USUBJID", "PARAMCD", "AVISIT")
join_keys(data)["ADTRWF"] <- c("STUDYID", "USUBJID", "PARAMCD", "AVISIT")
join_keys(data)["ADRSSWIM"] <- c("STUDYID", "USUBJID", "PARAMCD", "AVISIT")
join_keys(data)[["ADTR"]][["ADSL"]] <- c("STUDYID", "USUBJID")
join_keys(data)[["ADTRWF"]][["ADSL"]] <- c("STUDYID", "USUBJID")
join_keys(data)[["ADRSSWIM"]][["ADSL"]] <- c("STUDYID", "USUBJID")
```

File: exploratory/app.R [hunk 5]
```diff
@@ -1,62 +1,60 @@
...
-# <code
+    )
+})
+
+datanames <- c("ADSL", "ADRS", "ADLB", "ADLBPCA")
+datanames(data) <- datanames
+
+join_keys(data) <- default_cdisc_join_keys[datanames]
+join_keys(data)[["ADLBPCA"]][["ADLBPCA"]] <- c("USUBJID", "STUDYID", "PARAMCD", "AVISIT")
+join_keys(data)[["ADLBPCA"]][["ADSL"]] <- c("USUBJID", "STUDYID")
```
Comment (gogonzo) [inline exploratory/app.R:51]: There is a nice feature in `join_keys` which allows to change name of the dataset. Here "ADLBPCA" is a dataset obtained from ADLB - so we can reuse ADLB keys. I don't suggest this change here but I'd like to point out that is possible and you might prefer this in other places maybe. FYI to all

@vedhav @kartikeyakirar @chlebowa @m7pr @averissimo @donyunardi @pawelru 

```suggestion
join_keys(data) <- default_cdisc_join_keys[datanames]
adlbpca_keys <- default_cdisc_join_keys["ADLB"]
names(adlbpca_keys)[1] <- "ADLBPCA"
join_keys(data) <- c(join_keys(data), adlbpca_keys)
```

File: patient-profile/app.R [hunk 6]
```diff
@@ -1,42 +1,59 @@
...
+  )
+
+  ## Modify ADHM
+  ADMH[["MHDISTAT"]] <- "ONGOING"
+  teal.data::col_labels(ADMH[c("MHDISTAT")]) <- c("Status of Disease")
+})
+
+datanames <- c("ADSL", "ADMH", "ADAE", "ADCM", "ADVS", "ADLB")
+datanames(data) <- datanames
+join_keys(data) <- default_cdisc_join_keys[datanames]
```
Comment (kartikeyakirar) [inline patient-profile/app.R:47]:
```suggestion
join_keys(data) <- default_cdisc_join_keys[datanames]

join_keys(data)[["ADAE"]][["ADMH"]] <- c("STUDYID", "USUBJID")
join_keys(data)[["ADAE"]][["ADCM"]] <- c("STUDYID", "USUBJID")
join_keys(data)[["ADAE"]][["ADVS"]] <- c("STUDYID", "USUBJID")
join_keys(data)[["ADAE"]][["ADLB"]] <- c("STUDYID", "USUBJID")
join_keys(data)[["ADCM"]][["ADMH"]] <- c("STUDYID", "USUBJID")
join_keys(data)[["ADCM"]][["ADVS"]] <- c("STUDYID", "USUBJID")
join_keys(data)[["ADCM"]][["ADLB"]] <- c("STUDYID", "USUBJID")
join_keys(data)[["ADVS"]][["ADMH"]] <- c("STUDYID", "USUBJID")
join_keys(data)[["ADVS"]][["ADLB"]] <- c("STUDYID", "USUBJID")
join_keys(data)[["ADLB"]][["ADMH"]] <- c("STUDYID", "USUBJID")
```
tm_g_pp_patient_timeline module was failing.

Comment (gogonzo) [reply patient-profile/app.R:47]: Hmmm, I need to check it how it was before. If two datasets can be merged together by keys to their shared parent. Lemme think

Comment (kartikeyakirar) [reply patient-profile/app.R:47]: Old join key
```
> old_jk$get_join_keys()
A join_keys object containing foreign keys between 6 datasets:
ADSL: [STUDYID, USUBJID]
  <-- ADAE: [STUDYID, USUBJID]
  <-- ADMH: [STUDYID, USUBJID]
  <-- ADCM: [STUDYID, USUBJID]
  <-- ADVS: [STUDYID, USUBJID]
  <-- ADLB: [STUDYID, USUBJID]
ADAE: [STUDYID, USUBJID, ASTDTM, AETERM, AESEQ]
  --> ADSL: [STUDYID, USUBJID]
  <-> ADMH: [STUDYID, USUBJID]
  <-> ADCM: [STUDYID, USUBJID]
  <-> ADVS: [STUDYID, USUBJID]
  <-> ADLB: [STUDYID, USUBJID]
ADMH: [STUDYID, USUBJID, ASTDTM, MHSEQ]
  --> ADSL: [STUDYID, USUBJID]
  <-> ADAE: [STUDYID, USUBJID]
  <-> ADCM: [STUDYID, USUBJID]
  <-> ADVS: [STUDYID, USUBJID]
  <-> ADLB: [STUDYID, USUBJID]
ADCM: [STUDYID, USUBJID, ASTDTM, CMSEQ, ATC1CD, ATC2CD, ATC3CD, ATC4CD]
  --> ADSL: [STUDYID, USUBJID]
  <-> ADAE: [STUDYID, USUBJID]
  <-> ADMH: [STUDYID, USUBJID]
  <-> ADVS: [STUDYID, USUBJID]
  <-> ADLB: [STUDYID, USUBJID]
ADVS: [STUDYID, USUBJID, PARAMCD, AVISIT]
  --> ADSL: [STUDYID, USUBJID]
  <-> ADAE: [STUDYID, USUBJID]
  <-> ADMH: [STUDYID, USUBJID]
  <-> ADCM: [STUDYID, USUBJID]
  <-> ADLB: [STUDYID, USUBJID]
ADLB: [STUDYID, USUBJID, PARAMCD, AVISIT]
  --> ADSL: [STUDYID, USUBJID]
  <-> ADAE: [STUDYID, USUBJID]
  <-> ADMH: [STUDYID, USUBJID]
  <-> ADCM: [STUDYID, USUBJID]
  <-> ADVS: [STUDYID, USUBJID] 
```
New Join keys 
```
> join_keys(data) <- default_cdisc_join_keys[datanames]
> join_keys(data)
A join_keys object containing foreign keys between 6 datasets:
ADSL: [STUDYID, USUBJID]
  <-- ADAE: [STUDYID, USUBJID]
  <-- ADCM: [STUDYID, USUBJID]
  <-- ADLB: [STUDYID, USUBJID]
  <-- ADMH: [STUDYID, USUBJID]
  <-- ADVS: [STUDYID, USUBJID]
ADAE: [STUDYID, USUBJID, ASTDTM, AETERM, AESEQ]
  --> ADSL: [STUDYID, USUBJID]
ADCM: [STUDYID, USUBJID, ASTDTM, CMSEQ, ATC1CD, ATC2CD, ATC3CD, ATC4CD]
  --> ADSL: [STUDYID, USUBJID]
ADLB: [STUDYID, USUBJID, PARAMCD, AVISIT]
  --> ADSL: [STUDYID, USUBJID]
ADMH: [STUDYID, USUBJID, ASTDTM, MHSEQ]
  --> ADSL: [STUDYID, USUBJID]
ADVS: [STUDYID, USUBJID, PARAMCD, AVISIT]
  --> ADSL: [STUDYID, USUBJID] 
```

Comment (gogonzo) [reply patient-profile/app.R:47]: Ok, we need to resolve it in teal.data then

Comment (gogonzo) [reply patient-profile/app.R:47]: @kartikeyakirar Seems to be fixed. Thanks for catching this up early

File: exploratory/app.R (hunk 5 above)
Comment (vedhav) [reply exploratory/app.R]: I think some implicit mappings might go missing for `ADLBPCA` unless we explicitly connect `ADLBPCA` with `ADLB` because the `ADLB` is only connected with `ADSL` as a child and only this relationship is retained when we copy like this. We also need all the implicit connections from `ADLB` available for `ADLBPCA`

```r
join_keys(data) <- default_cdisc_join_keys[datanames]
adlbpca_keys <- default_cdisc_join_keys["ADLB"]
names(adlbpca_keys)[1] <- "ADLBPCA"
join_keys(data) <- c(join_keys(data), adlbpca_keys)
join_keys(data)
# ADLBPCA: [STUDYID, USUBJID, PARAMCD, AVISIT]
#   <-> ADSL: [STUDYID, USUBJID] 

join_keys(data)["ADLBPCA", "ADLB"] <- c("USUBJID", "STUDYID")
# ADLBPCA: [STUDYID, USUBJID, PARAMCD, AVISIT]
#   <-> ADSL: [STUDYID, USUBJID]
#   <-> ADLB: [USUBJID, STUDYID]

# For more accurate relationship mapping, although not needed
parents(data) <- c(parents(data), list(ADLBPCA = "ADLB"))
# ADLBPCA: [STUDYID, USUBJID, PARAMCD, AVISIT]
#   <-> ADSL: [STUDYID, USUBJID]
#   --> ADLB: [USUBJID, STUDYID]
```

Comment (gogonzo) [reply exploratory/app.R]: It makes me thinking if we should conclude implicit keys on grandchildren also @averissimo

File: exploratory/app.R [hunk 7]
```diff
@@ -1,62 +1,61 @@
...
-  vars = list(ADLB = adlb)
-)
-# <code
+    )
+})
+
+datanames <- c("ADSL", "ADRS", "ADLB", "ADLBPCA")
+datanames(data) <- datanames
+
+join_keys(data) <- default_cdisc_join_keys[datanames]
```
Comment (kartikeyakirar) [inline exploratory/app.R:49]: should we exclude `ADSLPCA` since it is not present in the default_cdisc_join_keys. Instead, we should simply use c("ADSL", "ADRS", "ADLB").to enhance clarity in the subsequent step ?

Comment (gogonzo) [reply exploratory/app.R:49]: Makes sense to `default_cdisc_join_keys[c("ADSL", "ADRS", "ADLB")] # no ADLBPCA defaults`

File: exploratory/app.R (hunk 5 above)
Comment (vedhav) [reply exploratory/app.R]: These examples will confuse me as a new user who does not know the mechanics of join_keys. We should encourage people to create their own keys from scratch, chances are their keys have nothing to do with our default set of keys.

And I think that parent mappings are not copied when we do a `c` merge of join keys.

```r
jk_adlbpca <- join_keys(
  join_key("ADLBPCA", "ADLBPCA", c("STUDYID", "USUBJID", "PARAMCD", "AVISIT")),
  join_key("ADLBPCA", "ADLB", c("STUDYID", "USUBJID", "PARAMCD", "AVISIT"))
)
parents(jk_adlbpca) <- list(ADLBPCA = "ADLB")

jk <- default_cdisc_join_keys["ADLB"]
jk <- c(jk, jk_adlbpca)
parents(jk)
# $ADLB
# [1] "ADSL"
parents(jk) <- c(parents(jk), list("ADLBPCA" = "ADLB"))
parents(jk)
# $ADLB
# [1] "ADSL"
#
# $ADLBPCA
# [1] "ADLB"
```

File: exploratory/app.R (hunk 7 above)
Comment (vedhav) [reply exploratory/app.R:49]: I think it's just a matter of DRY here. We already store the datanames in a variable so it's convenient to do a subset like this. Now it's okay, previously we used to get a join key set for `ADLB` with NULL.

File: early-dev/app.R [hunk 8]
```diff
@@ -1,141 +1,178 @@
...
+      LBSTRESN = "Numeric Result/Finding in Standard Units"
+    )
+})
+
+# set datanames
+datanames <- c("ADSL", "ADAE", "ADCM", "ADEX", "ADTR", "ADTRWF", "ADRS", "ADRSSWIM", "ADLB")
+datanames(data) <- datanames
+
+# set join keys
+join_keys(data) <- default_cdisc_join_keys[datanames] # get default keys by name
```
[the remark this answers is not in the document]
Comment (gogonzo) [reply early-dev/app.R:148]: Thanks @kartikeyakirar 
The second is the old class which will be removed next week. In old classes `update_keys_given_parent` are run in a different moment so the keys are hardcoded in a list. 
Both lists will work as expected, where the second one won't be here anymore.

**Comment by vedhav** [comment]
Please merge this PR #96 and merge the `main` into `dev` before merging this PR targeting the`dev` branch.

**Review by kartikeyakirar — APPROVED** [review]
I've tested all the applications, and none of them have encountered any failures in any module.
